### ISSUE TITLE
does not compile with ui

### ISSUE THREAD

**Issue by ghost** [Larpon/jni#7]
**OS: ArchLinux**

**V version: 0.2.2 3879652**

**What did you do?**
added toast_ui.v instead of toast.v in ~/.vmodules/jni/examples/android/toast/

```v
import ui
import jni
import jni.auto

const (
	pkg      = 'io.v.android.ex.VToastActivity'
)

[export: 'JNI_OnLoad']
fn jni_on_load(vm &jni.JavaVM, reserved voidptr) int {
	println(@FN + ' called')
	jni.set_java_vm(vm)
	$if android {
		// V consts - can't be used since `JNI_OnLoad`
		// is called by the Java VM before the lib
		// with V's init code is loaded and called.
		jni.setup_android('io.v.android.ex.VToastActivity')
	}
	return C.JNI_VERSION_1_6
}

fn show_toast(text string) {
	println(@FN + ': "$text"')
	$if android {
		jor := auto.call_static_method(jni.sig(pkg, @FN, 'void', text), text)
		println('V jni.CallResult: $jor showing toast')
	}
}

fn main(){
	window := ui.window({
		width: 300
		height: 300
		on_click: click
	},[])
	ui.run(window)
}

fn click(e ui.MouseEvent, window &ui.Window){
	show_toast('Hello from UI')
}
```

```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export ANDROID_NDK_ROOT=$HOME/Android/Sdk/ndk
export VEXE=$HOME/lang/v/v
cd $HOME/.vmodules/vab
~/.vmodules/vab% ./vab run --api 24 --device auto --archs 'armeabi-v7a' -v 3 ~/.vmodules/jni/examples/android/toast
Using package id "io.v.android.ex" from .vab file "/home/tsukasa/.vmodules/jni/examples/android/toast/.vab"
Using package id "VToastActivity" from .vab file "/home/tsukasa/.vmodules/jni/examples/android/toast/.vab"
Notice: Android API level 24 is less than the recomended level (30).
Should run "io.v.android.ex/io.v.android.ex.VToastActivity"
Compiling V to C
Running /home/tsukasa/lang/v/v
/home/tsukasa/lang/v/v -dump-c-flags "/tmp/vab/v.cflags" -os android -apk /home/tsukasa/.vmodules/jni/examples/android/toast
Running /home/tsukasa/lang/v/v
/home/tsukasa/lang/v/v -os android -apk -o "/tmp/vab/v_android.c" /home/tsukasa/.vmodules/jni/examples/android/toast

Writing new hash 9adeff8fffef606f099b3990c1cc83d8
Compiling C to ['armeabi-v7a']
Using GLES 2
Running /home/tsukasa/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang
/home/tsukasa/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang -O0 -fPIC -fvisibility=hidden -ffunction-sections -fdata-sections -ferror-limit=1 -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-unused-result -Wno-unused-function -Wno-missing-braces -Wno-unused-label -Werror=implicit-function-declaration -Wno-braced-scalar-init -Wno-incompatible-pointer-types -Wno-implicitly-unsigned-literal -Wno-pointer-sign -Wno-enum-conversion -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-sign-compare -Wno-return-type -Wno-extra-tokens -I "/home/tsukasa/.vmodules/jni/c" -I "/home/tsukasa/lang/v/thirdparty/fontstash" -I "/usr/local/Cellar/freetype/2.10.2/include/freetype2" -I "/home/tsukasa/lang/v/thirdparty/stb_image" -I "/home/tsukasa/lang/v/thirdparty/sokol" -I "/home/tsukasa/lang/v/thirdparty/sokol/util" -I"/home/tsukasa/Android/Sdk/ndk/21.4.7075529/sysroot/usr/include" -I"/home/tsukasa/Android/Sdk/ndk/21.4.7075529/sysroot/usr/include/android" -DAPPNAME="v_test_app" -DANDROID -D__ANDROID__ -DANDROIDVERSION=24 -DANDROID_FULLSCREEN -DSOKOL_GLES2 "/home/tsukasa/lang/v/thirdparty/stb_image/stbi.c" -mfloat-abi=softfp -m32 -o "/tmp/vab/build/lib/armeabi-v7a/libv_test_app.so" /tmp/vab/v_android.c -L"/home/tsukasa/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/24" -lm -lc -uANativeActivity_onCreate -usokol_main -llog -landroid -lEGL -lGLESv2 -lm -shared
/home/tsukasa/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang failed with return code 1
In file included from /tmp/vab/v_android.c:910:
/home/tsukasa/.vmodules/jni/c/helpers.h:23:3: error: implicit declaration of function '__android_log_print' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                V_JNI_ANDROID_LOG_I(fmt, args);
                ^
/home/tsukasa/.vmodules/jni/c/helpers.h:8:34: note: expanded from macro 'V_JNI_ANDROID_LOG_I'
#define V_JNI_ANDROID_LOG_I(...) __android_log_print(ANDROID_LOG_INFO, V_JNI_ANDROID_LOG_TAG, __VA_ARGS__)
                                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 errors generated.
```

When compiled, got this error.

```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export ANDROID_NDK_ROOT=$HOME/Android/Sdk/ndk
export VEXE=$HOME/lang/v/v
cd $HOME/.vmodules/vab
~/.vmodules/vab% ./vab run --api 24 --device auto --archs 'armeabi-v7a' -v 3 ~/.vmodules/jni/examples/android/toast
Using package id "io.v.android.ex" from .vab file "/home/tsukasa/.vmodules/jni/examples/android/toast/.vab"
Using package id "VToastActivity" from .vab file "/home/tsukasa/.vmodules/jni/examples/android/toast/.vab"
Notice: Android API level 24 is less than the recomended level (30).
Should run "io.v.android.ex/io.v.android.ex.VToastActivity"
Compiling V to C
Running /home/tsukasa/lang/v/v
/home/tsukasa/lang/v/v -dump-c-flags "/tmp/vab/v.cflags" -os android -apk /home/tsukasa/.vmodules/jni/examples/android/toast
Running /home/tsukasa/lang/v/v
/home/tsukasa/lang/v/v -os android -apk -o "/tmp/vab/v_android.c" /home/tsukasa/.vmodules/jni/examples/android/toast

Skipping compile. Hashes match fb0cb6cf1be88ceec126afc036a24846
Preparing package "io.v.android.ex"...
Removing previous package directory /tmp/vab/package/apk
Copying base files from /home/tsukasa/.vmodules/vab/platforms/android to /tmp/vab/package/apk
/home/tsukasa/.vmodules/vab/platforms/android/src/io/v/android/VActivity.java
/home/tsukasa/.vmodules/vab/platforms/android/res/values/strings.xml
/home/tsukasa/.vmodules/vab/platforms/android/res/mipmap/icon.png
/home/tsukasa/.vmodules/vab/platforms/android/AndroidManifest.xml
Copying base files from /home/tsukasa/.vmodules/jni/examples/android/toast/java to /tmp/vab/package/apk
/home/tsukasa/.vmodules/jni/examples/android/toast/java/src/io/v/android/ex/VToastActivity.java
/home/tsukasa/.vmodules/jni/examples/android/toast/java/res/values/strings.xml
/home/tsukasa/.vmodules/jni/examples/android/toast/java/res/mipmap/icon.png
/home/tsukasa/.vmodules/jni/examples/android/toast/java/AndroidManifest.xml
Modifying base files
Modifying native activity "/tmp/vab/package/apk/src/io/v/android/VActivity.java"
Skipping replacing package id since "io.v.android.ex" is user provided
Replacing init library "v" with "v_test_app"
Copying assets
Running /home/tsukasa/Android/Sdk/build-tools/30.0.3/aapt
/home/tsukasa/Android/Sdk/build-tools/30.0.3/aapt package -v -f -m -M /tmp/vab/package/apk/AndroidManifest.xml -S /tmp/vab/package/apk/res -J /tmp/vab/package/apk/src -A /tmp/vab/package/apk/assets -I /home/tsukasa/Android/Sdk/platforms/android-24/android.jar
Compiling java sources
Running /usr/lib/jvm/java-8-openjdk/bin/javac
/usr/lib/jvm/java-8-openjdk/bin/javac -d obj -source 1.7 -target 1.7 -classpath . -sourcepath src -bootclasspath /home/tsukasa/Android/Sdk/platforms/android-24/android.jar /tmp/vab/package/apk/src/io/v/android/ex/R.java /tmp/vab/package/apk/src/io/v/android/ex/VActivity.java /tmp/vab/package/apk/src/io/v/android/ex/VToastActivity.java
Running /home/tsukasa/Android/Sdk/build-tools/30.0.3/dx
/home/tsukasa/Android/Sdk/build-tools/30.0.3/dx --verbose --dex --output=bin/classes.dex obj
Running /home/tsukasa/Android/Sdk/build-tools/30.0.3/aapt
/home/tsukasa/Android/Sdk/build-tools/30.0.3/aapt package -v -f -S /tmp/vab/package/apk/res -M /tmp/vab/package/apk/AndroidManifest.xml -A /tmp/vab/package/apk/assets -I /home/tsukasa/Android/Sdk/platforms/android-24/android.jar -F /tmp/vab/v_test_app.unaligned.apk bin
Running /home/tsukasa/Android/Sdk/build-tools/30.0.3/zipalign
/home/tsukasa/Android/Sdk/build-tools/30.0.3/zipalign -v -f 4 /tmp/vab/v_test_app.unaligned.apk /tmp/vab/v_test_app.unsigned.apk
Running /home/tsukasa/Android/Sdk/build-tools/30.0.3/apksigner
/home/tsukasa/Android/Sdk/build-tools/30.0.3/apksigner sign --ks "/home/tsukasa/.vmodules/vab/debug.keystore" --ks-pass pass:android --ks-key-alias "androiddebugkey" --key-pass pass:android --out /tmp/vab/v_test_app.apk /tmp/vab/v_test_app.unsigned.apk
Running /home/tsukasa/Android/Sdk/build-tools/30.0.3/apksigner
/home/tsukasa/Android/Sdk/build-tools/30.0.3/apksigner verify -v /tmp/vab/v_test_app.apk
Moving product from "/tmp/vab/v_test_app.apk" to "v_test_app.apk"
Running /home/tsukasa/Android/Sdk/platform-tools/adb
/home/tsukasa/Android/Sdk/platform-tools/adb devices -l
Deploying apk package to "03157df3bb786518"
Running /home/tsukasa/Android/Sdk/platform-tools/adb
/home/tsukasa/Android/Sdk/platform-tools/adb -s "03157df3bb786518" install -r v_test_app.apk
Running "io.v.android.ex/io.v.android.ex.VToastActivity" on "03157df3bb786518"
Running /home/tsukasa/Android/Sdk/platform-tools/adb
/home/tsukasa/Android/Sdk/platform-tools/adb -s "03157df3bb786518" shell am start -n io.v.android.ex/io.v.android.ex.VToastActivity
Running /home/tsukasa/Android/Sdk/platform-tools/adb
/home/tsukasa/Android/Sdk/platform-tools/adb -s 03157df3bb786518 logcat --buffer=crash -d
It looks like your app might have crashed
Dumping crash buffer:
06-01 15:08:17.775 18906 18906 E AndroidRuntime: FATAL EXCEPTION: main
06-01 15:08:17.775 18906 18906 E AndroidRuntime: Process: io.v.android.ex, PID: 18906
06-01 15:08:17.775 18906 18906 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.v.android.ex-1/base.apk"],nativeLibraryDirectories=[/data/app/io.v.android.ex-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libv_test_app.so"
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:972)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1567)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at io.v.android.VActivity.<clinit>(VActivity.java:6)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1086)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6682)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
06-01 15:08:17.775 18906 18906 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
06-01 15:08:38.497 19481 19481 E AndroidRuntime: FATAL EXCEPTION: main
06-01 15:08:38.497 19481 19481 E AndroidRuntime: Process: io.v.android.ex, PID: 19481
06-01 15:08:38.497 19481 19481 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.v.android.ex-2/base.apk"],nativeLibraryDirectories=[/data/app/io.v.android.ex-2/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libv_test_app.so"
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:972)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1567)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at io.v.android.VActivity.<clinit>(VActivity.java:6)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1086)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6682)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
06-01 15:08:38.497 19481 19481 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
06-01 15:09:28.087 20690 20690 E AndroidRuntime: FATAL EXCEPTION: main
06-01 15:09:28.087 20690 20690 E AndroidRuntime: Process: io.v.android.ex, PID: 20690
06-01 15:09:28.087 20690 20690 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.v.android.ex-1/base.apk"],nativeLibraryDirectories=[/data/app/io.v.android.ex-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libv_test_app.so"
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:972)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1567)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at io.v.android.VActivity.<clinit>(VActivity.java:6)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1086)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6682)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
06-01 15:09:28.087 20690 20690 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

You can clear all logs by running:
"/home/tsukasa/Android/Sdk/platform-tools/adb -s "03157df3bb786518" logcat -c"
Deployed to device (auto) successfully
```

**What did you expect to see?**

**What did you see instead?**

**Comment by larpon** [comment]
@kahsa - now it compiles, I had to adjust your code due to recent V changes;
```v
import ui
import jni
import jni.auto

const (
	pkg      = 'io.v.android.ex.VToastActivity'
)

[export: 'JNI_OnLoad']
fn jni_on_load(vm &jni.JavaVM, reserved voidptr) int {
	println(@FN + ' called')
	jni.set_java_vm(vm)
	$if android {
		// V consts - can't be used since `JNI_OnLoad`
		// is called by the Java VM before the lib
		// with V's init code is loaded and called.
		jni.setup_android('io.v.android.ex.VToastActivity')
	}
	return C.JNI_VERSION_1_6
}

fn show_toast(text string) {
	println(@FN + ': "$text"')
	$if android {
		jor := auto.call_static_method(jni.sig(pkg, @FN, 'void', text), text)
		println('V jni.CallResult: $jor showing toast')
	}
}

fn main(){
	window := ui.window(
		width: 300
		height: 300
		on_click: click
	)
	ui.run(window)
}

fn click(e ui.MouseEvent, window &ui.Window){
	show_toast('Hello from UI')
}
```

But on my phone I just get a short flash with a black screen, before the app then closes. I hope you can take it from there.

**Comment by ghost** [comment]
```v
import ui
// import jni
// import jni.auto

// const (
// 	pkg      = 'io.v.android.ex.VToastActivity'
// )

// [export: 'JNI_OnLoad']
// fn jni_on_load(vm &jni.JavaVM, reserved voidptr) int {
// 	println(@FN + ' called')
// 	jni.set_java_vm(vm)
// 	$if android {
// 		// V consts - can't be used since `JNI_OnLoad`
// 		// is called by the Java VM before the lib
// 		// with V's init code is loaded and called.
// 		jni.setup_android('io.v.android.ex.VToastActivity')
// 	}
// 	return C.JNI_VERSION_1_6
// }

// fn show_toast(text string) {
// 	println(@FN + ': "$text"')
// 	$if android {
// 		jor := auto.call_static_method(jni.sig(pkg, @FN, 'void', text), text)
// 		println('V jni.CallResult: $jor showing toast')
// 	}
// }

fn main(){	
	window := ui.window(
		width: 300
		height: 300
		// on_click: click
		children: [ui.column()])
	ui.run(window)
}

// fn click(e ui.MouseEvent, window &ui.Window){
// 	// show_toast('Hello from UI')
// }
```

This works on linux but faield on android with this error.

```
08-30 19:31:48.589 19555 19594 E test    : V panic: 
08-30 19:31:48.589 19555 19594 E test    : none
08-30 19:31:48.589 19555 19594 E test    : v hash: 61ac7b6
```

Don't know what this error means.
So the cause may be something else.

**Comment by larpon** [comment]
In this case I think it's an issue with V UIs android compatibility. Can you please open an issue in vui?

**Comment by ghost** [comment]
I think so. but where is the problem.
Anyway, in other my android program, jni works fine.
Thanks.

**Comment by larpon** [comment]
> I think so. but where is the problem.
> Anyway, in other my android program, jni works fine.
> Thanks.

I think you might need to set `window.state` to a valid pointer. I've looked at UI's code and can see that all calls just assume that there's something there :(

**Comment by ghost** [comment]
ok, it was font issue.
Adding `toast/assets/fonts/font.ttf` resolved this.

**Comment by larpon** [comment]
Cool you managed to track it down. Yeah it's a challenge to fix these kinds of errors where some asset is expected to be present :thinking:

**Comment by larpon** [comment]
> ok, it was font issue.
> Adding `toast/assets/fonts/font.ttf` resolved this.

Was it in your own code or a problem with V's font code?
I can't see any entries of `fonts/font.ttf` in any of the code bases?

**Comment by ghost** [comment]
your example `jni/examples/android/toast/` doesn't have asset folder.

**Comment by ghost** [comment]
Don't know what is the best practice adding font in android program tho..

**Comment by larpon** [comment]
> your example `jni/examples/android/toast/` doesn't have asset folder.

No it doesn't because it doesn't use any fonts?
I can't reproduce it on my setup, that's why I asked 🙂

**Comment by ghost** [comment]
You can't??
What I did is..

```
~/.vmodules/.../android/toast% tree
.
├── assets
│   ├── fonts
│   │   ├── LICENSE
│   │   └── RobotoMono-Regular.ttf
│   └── img
│       └── logo.png
├── java
│   ├── AndroidManifest.xml
│   ├── res
│   │   ├── mipmap
│   │   │   └── icon.png
│   │   └── values
│   │       └── strings.xml
│   └── src
│       └── io
│           └── v
│               └── android
│                   └── ex
│                       └── VToastActivity.java
├── toast.v_
└── toast_ui.v
```

toast_ui.v is https://github.com/Larpon/jni/issues/7#issuecomment-908239449

Just added assets folder and replaced `toast.v` with `toast_ui.v`

```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export ANDROID_NDK_ROOT=$HOME/Android/Sdk/ndk
export VEXE=$HOME/lang/v/v

cd $HOME/.vmodules/vab

APP=$HOME/.vmodules/jni/examples/android/toast

./vab run --api 24 --device auto --archs 'armeabi-v7a' \
    --name Test --package-id com.kahsa.testapp \
    -v 3 \
    --log \
    $APP
```

This works.
And comment out also works.
```v
import ui
import jni
import jni.auto

const (
	pkg      = 'io.v.android.ex.VToastActivity'
)

[export: 'JNI_OnLoad']
fn jni_on_load(vm &jni.JavaVM, reserved voidptr) int {
	println(@FN + ' called')
	jni.set_java_vm(vm)
	$if android {
		// V consts - can't be used since `JNI_OnLoad`
		// is called by the Java VM before the lib
		// with V's init code is loaded and called.
		jni.setup_android('io.v.android.ex.VToastActivity')
	}
	return C.JNI_VERSION_1_6
}

fn show_toast(text string) {
	println(@FN + ': "$text"')
	$if android {
		jor := auto.call_static_method(jni.sig(pkg, @FN, 'void', text), text)
		println('V jni.CallResult: $jor showing toast')
	}
}

fn main(){	
	window := ui.window(
		width: 300
		height: 300
		on_click: click
		children: [ui.column()])
	ui.run(window)
}

fn click(e ui.MouseEvent, window &ui.Window){
	show_toast('Hello from UI')
}
```

**Comment by ghost** [comment]
https://github.com/vlang/ui/blob/1b44ca12481b7a174a240887c7f0982fa0638f4f/window.v#L413

Ok, this is the cause.

**Comment by larpon** [comment]
Yes got it now, thanks!
